SELECT
	DISTINCT(US.USR_ID) CODIGO,
	US.USR_NOME NOME,
	MP.M_NAME,
	DES.N_DESC,
	MF.F_FUNCTION,
	CASE
	 WHEN US.USR_MSBLQL='1' THEN 'Sim'
	 WHEN US.USR_MSBLQL='2' THEN 'Nao'
	End AS BLOQUEADO,
	MD.USR_CODMOD,
	CONVERT(VARCHAR, CONVERT(DATE, US.USR_DTINC),103) AS USR_DTINC,
	US.USR_QTDEXPPSW,
	US.USR_REDTBS,
	US.USR_AVDTBS
FROM
	SYS_USR US
	
JOIN SYS_USR_MODULE MD ON
	MD.USR_ID = US.USR_ID
	AND MD.D_E_L_E_T_ = ''
JOIN MPMENU_MENU MP ON
	MP.D_E_L_E_T_ = ''
	AND MP.M_ID = MD.USR_ARQMENU
	AND MD.USR_MODULO = MP.M_MODULE
JOIN MPMENU_ITEM MI ON
	MI.D_E_L_E_T_ = ''
	AND MI.I_ID_MENU = MP.M_ID
JOIN MPMENU_FUNCTION MF ON
	MF.D_E_L_E_T_ = ''
	AND MF.F_ID = MI.I_ID_FUNC
JOIN MPMENU_I18N DES ON
	DES.D_E_L_E_T_ = ''
	AND DES.N_LANG = '1'
	AND DES.N_PAREN_ID = MI.I_FATHER
WHERE
	US.D_E_L_E_T_ = ''
	AND MD.USR_ACESSO = 'T'
	AND US.USR_MSBLQL<>'1'
ORDER BY
	MP.M_NAME