WITH DADOS AS (
    SELECT 
        MENU.M_ID AS ROOTMENUID,
        TRIM(MENU.M_NAME) AS ROOTMENUNAME,
        ITEM.I_ID,
        ITEM.I_FATHER,
        ITEM.I_TP_MENU,
        TRIM(I18M.N_DESC) AS MENUDESC,
        TRIM(I18I.N_DESC) AS ITEMDESC,
        ISNULL(FUNC.F_FUNCTION, '') AS FUNCTIONNAME
    FROM MPMENU_MENU MENU
    JOIN MPMENU_I18N I18M 
        ON I18M.N_PAREN_ID = MENU.M_ID
       AND I18M.N_PAREN_TP = 1
       AND I18M.D_E_L_E_T_ = ' '
    JOIN MPMENU_ITEM ITEM 
        ON ITEM.I_ID_MENU = MENU.M_ID
       AND ITEM.D_E_L_E_T_ = ' '
    LEFT JOIN MPMENU_I18N I18I 
        ON I18I.N_PAREN_ID = ITEM.I_ID
       AND I18I.N_PAREN_TP = 2
       AND I18I.N_LANG = 1
       AND I18I.D_E_L_E_T_ = ' '
    LEFT JOIN MPMENU_FUNCTION FUNC 
        ON FUNC.F_ID = ITEM.I_ID_FUNC
    WHERE MENU.M_NAME NOT LIKE '#BKP_%'
      AND MENU.D_E_L_E_T_ = ' '
),
RECURSIVEMENU AS (
    SELECT 
        DD.I_ID,
        DD.I_TP_MENU,
        DD.ROOTMENUNAME,
        DD.MENUDESC,
        CAST(DD.ITEMDESC AS VARCHAR(MAX)) AS FULLPATH,
        DD.FUNCTIONNAME
    FROM DADOS DD
    WHERE DD.I_FATHER = DD.ROOTMENUID

    UNION ALL

    SELECT 
        DD.I_ID,
        DD.I_TP_MENU,
        DD.ROOTMENUNAME,
        DD.MENUDESC,
        CAST(RM.FULLPATH + '/' + COALESCE(DD.ITEMDESC, DD.I_ID) AS VARCHAR(MAX)) AS FULLPATH,
        DD.FUNCTIONNAME
    FROM RECURSIVEMENU RM
    JOIN DADOS DD 
        ON DD.I_FATHER = RM.I_ID
)
SELECT 
    RM.ROOTMENUNAME,
    RM.MENUDESC,
    RM.FULLPATH,
    RM.FUNCTIONNAME
FROM RECURSIVEMENU RM
WHERE RM.I_TP_MENU = 2
  AND RM.FUNCTIONNAME = 'MATA410'
ORDER BY RM.ROOTMENUNAME, RM.FULLPATH;
